version: '3.18'
services:
  frontend:
    build:
      context: .
      target: "${FRONT_DOCKER_TARGET}"
    image: "passgo-frontend-img-${FRONT_DOCKER_TARGET}"
    env_file:
      - path: '.env.${FRONT_ENV_TAG}'
        required: true
    pull_policy: build
    container_name: "${FRONT_PROJECT_NAME}"
    ports:
      - "${FRONT_HOST_PORT}:${FRONT_CONTAINER_PORT}"
    networks:
      - passgo-network

networks:
  passgo-network:
    name: passgo-network
    external: true